export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const REGISTER_NEW_USER = "REGISTER_NEW_USER";


export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_START = "LOGIN_START";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_ITEM = "ADD_CATEGORY_ITEM";
